### ISSUE TITLE
Compatibility with ESP8266?

### ISSUE THREAD

**Issue by blark** [wizard97/ArduinoRingBuffer#2]
Hi there,

I was hoping to use your library on the ESP8266, but I get the following error:

```
...snip...
WARNING: library RingBuf claims to run on [avr] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).
C:\Users\blark\Documents\Arduino\libraries\RingBuf\RingBuf.c:9:25: fatal error: util/atomic.h: No such file or directory

 #include <util/atomic.h>
...snip...
```

I took a look and it seems that atomic operations are possible on the ESP8266 (http://www.esp8266.com/viewtopic.php?f=9&t=618) however atomic.h is not implemented. Probably some wifi-related reason. Is there any hope of getting the code working on this platform?

**Comment by wizard97** [comment]
Hi,

Yeah, the problem is there is no `atomic.h` header for the ESP8266, which exist for the ATMega's. The only macro actually being used from `atomic.h` is:

```
ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
{
}
```

The easiest quick fix to is to remove the `#include <util/atomic.h>` and remove the `ATOMIC_BLOCK(ATOMIC_RESTORESTATE)` macro. Then you just manually make sure that an interrupt won't fire during any method call using noInterrupts() and interrupts() from `Arduino.h`.

For example

```
noInterrupts(); // Prevent interrupts
// In here do whatever you like with the ring buffer.
buf->add(buf, &foo);
interrupts(); // Allow interrupts
```

I looked to see if there was an easy way to implement atomicy on the ESP8266, but I couldn't find anything short of writing inline assembly on the interrupt registers. Hope this solution though is sufficient for your needs!

**Comment by wizard97** [comment]
Now that I think of it, there is the possibility that you wouldn't need atomicy for the ESP8266. The only reason it is needed on the ATMegas is because they are 8 bit and can't do integer operation in a single instruction. This allows for the extremely rare possibility of an interrupt firing right when you are in the middle of an integer operation, which in rare circumstances can seriously corrupt things.

This might not be a problem on the ESP8266 since it has a a 32bit CPU, so you might be able to remove all the atomic stuff entirely.

**Comment by blark** [comment]
I made the changes and so far so good, but I haven't used it extensively yet. I'll let you know how it goes when I start using it more, which should be very soon in my current project. Thanks for the help.

**Comment by wizard97** [comment]
Awesome,

Glad to help! I hope everything works well, let me know if you find any more issues.

**Comment by blark** [comment]
Just experimented a little more. After several thousand push/pulls from the buffer everything seems to be working well.

**Comment by wizard97** [comment]
Awesome glad to see you got it working on the ESP8266 platform! Thanks for letting me know.

**Comment by wizard97** [comment]
I finally found the macros I needs to support the ESP8266 out of the box. The newest version (2.0) now supports it. https://github.com/wizard97/ArduinoRingBuffer/commit/efd76254e5fdf447527b120206cfe6ad2c367d4b
